# Generated by Django 3.2.9 on 2021-11-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_like_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
    ]
