# Generated by Django 3.2.9 on 2021-11-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.CharField(default='', max_length=300),
        ),
    ]
