# Generated by Django 3.2.9 on 2021-11-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211126_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='blog',
            new_name='comment',
        ),
    ]
